#dist: xenial

language: go
sudo: false
notifications:
  email: false

go:
  - 1.9.2

go_import_path: github.com/cagedmantis/sabre

install:
 - go get -u github.com/golang/dep/cmd/dep

script:
  - dep ensure
  - make
